services:
  - type: web
    name: blog-app
    runtime: ruby
    region: singapore
    plan: free
    buildCommand: bundle install && bundle exec rake assets:precompile assets:clean
    startCommand: bundle exec rake db:migrate && bundle exec rails server -p $PORT -b 0.0.0.0 -e production
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog-app-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production

databases:
  - name: blog-app-db
    databaseName: blog_app_production
    user: blog_user
    plan: free
    region: singapore