services:
  - type: web
    name: blog-app
    runtime: ruby
    region: singapore
    plan: free
    buildCommand: bundle install && bundle exec rake assets:precompile assets:clean db:migrate
    startCommand: bundle exec rails server -b 0.0.0.0 -p $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog-app-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: BUNDLE_WITHOUT
        value: development:test
      - key: WEB_CONCURRENCY
        value: 2

databases:
  - name: blog-app-db
    databaseName: blog_app_production
    user: blog_user
    plan: free
    region: singapore