default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_app_development
  username: asyraf
  password: asyraf
  host: localhost

test:
  <<: *default
  database: blog_app_test
  username: asyraf
  password: asyraf
  host: localhost

production:
  primary:
    <<: *default
    url: <%= ENV['postgresql://blog_user:ogfSifYw3TfLonsWnj8k9XDrM8BCLTUG@dpg-d4be10npm1nc73bo4mfg-a.singapore-postgres.render.com/blog_app_production_saom'] %>
  cache:
    <<: *default
    url: <%= ENV['postgresql://blog_user:ogfSifYw3TfLonsWnj8k9XDrM8BCLTUG@dpg-d4be10npm1nc73bo4mfg-a.singapore-postgres.render.com/blog_app_production_saom'] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    url: <%= ENV['postgresql://blog_user:ogfSifYw3TfLonsWnj8k9XDrM8BCLTUG@dpg-d4be10npm1nc73bo4mfg-a.singapore-postgres.render.com/blog_app_production_saom'] %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    url: <%= ENV['postgresql://blog_user:ogfSifYw3TfLonsWnj8k9XDrM8BCLTUG@dpg-d4be10npm1nc73bo4mfg-a.singapore-postgres.render.com/blog_app_production_saom'] %>
    migrations_paths: db/cable_migrate