default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_app_development
  username: asyraf
  password: asyraf
  host: localhost

test:
  <<: *default
  database: blog_app_test
  username: asyraf
  password: asyraf
  host: localhost

production:
  <<: *default
  url: <%= ENV['postgresql://blog_user:ogfSifYw3TfLonsWnj8k9XDrM8BCLTUG@dpg-d4be10npm1nc73bo4mfg-a/blog_app_production_saom'] %>